---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGO_ROOT_PASSWORD: AgBGXfv4kYkOLETxcRZm0S5v4lHEKi/WPQov1/lQErNg8I4Z7pMfX990Q/X9gBEKFy34Yo4iamwL/2cYlUgw9QGoXrc0WAmSu1MYJZFOJFz+Lt5jjUen1FUnJqQzx/iv7bL0XteO2ssEnvEaUGgCcsgX0p/q0dDYa4znW3vEHj0X1VufGyiCj9A9O/rT7PygVMuLh6fr8UVYhhzkMIiqTrICXanGjVuaG+zLNkw15YhRU3tMsl987f22LXHTG4o0vZ3sf14sHNktDXNnwAoyaxLFbNpx/uw0dG+98nSPQPjNSu6C6qcabHG+hqDfq3fDX2LLaj8wknfSQMsFJ5KiacxwGGTVF3KtEkJCJb5/BRLIXDuQ+Zrauo1W4mWYBieP75NdpS/zojr2YBA4/d0+k8Td4Cf6q1vQjCT0OcrP5GfAp47m3YSwSrw9YYepUuWiobmC0dgypCQpRG+l7S27a/0QmIA5hUVa+82BSi820wNkYS38D4GOiOkVdKJ64euzaHCunKrXUWn/7Rpj9C2d2LaKklFJLiWBtFArWkHscGDrtnwr5yQJDKS48ea7JZ/p7WhQQx9Qxg8tzBIDSMr0Nhox0wNHqhKlddOA2MPMyEYOPfT0+v2Dc7TryYpWGwvCoqsjgpHT2vnqRz0XhjYap7MuaW8o00FOyg/hBzi6eurH610a35+jIEOhb2FjpXZbM4jWi0OvFu+ia8NFAA==
    MONGO_ROOT_USERNAME: AgCabudmX7wOxppReYAUZ2b+xWqRHWzaW8F09/thC/PBRnlpPkp2vzaZp0X5R9nrVdySXrj6X9DRFxc54ttVflI9gWajP2SY7FR5GKl9PJcw2ZlTiGQz4jGEzz0cx3Zr/Y1LQ7DB9hesPTOYtTzirXQBEjahg2Qw57ySrntrNKKTDOlgSR41/Jg44WjxqTCu6SH85g9Pqe1DNhdE1Eh4EJZlxqW0tkC98EAQGhqQB1yj//XXllSjjQKVbyQ7+EGmw3X+NLfjRJmFUNhVeorJovbet8gBcHm85ZYhHnhctwEyce6+VRNsXLC6zGPvkh2wE1IY8ow9sCAv5Bp/FoFJEt/ow9NDkNqse7RV75Mngazl4MO7itmtmTJbfcUup4YZA00Di7uQ4LaT4zK7Tz7hXYBOu7nn2VJ4t/cQvZ54mwBcL+DOMa1H+lqBiK0Od4kODmPukjPcAMB+9lHee16MKUr7laxiYutPcWaxrLxIpXPitPxorEIUa4Sz7wtO4Zyupvp3DFAGBAfEia8uQDDZ1wBO/du8lKc/uY3SvFDmAIwRUp+KF7Jyk/D3jHWXvVm1Vy+cuhrj8TemeS/AbR0tu4wvdWAypLDsAp0J58xPE+wnFUgCxw74UrBZCk5qnJBKgc+46F9fBfqRMbMivTrJ99oCGjGvUuO/7Vju/lf8Hy3lasIucX8gAlfkvWGdg988WOnRr2O2Mg==
  template:
    metadata:
      name: mongo-secret
      namespace: default
    type: Opaque
