apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - keycloak-deployment.yaml
  - keycloak-service.yaml
  - keycloak-ingress.yaml
  - keycloak-pvc.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - oauth2-proxy-configmap.yaml
  - oauth2-proxy-secret.yaml
  - oauth2-proxy-ingress.yaml