apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded: your-client-secret-here (cambiar por el real de Keycloak despu√©s)
  client-secret: R2JiWTFzUmhlREpWb2R2emhtOEEySDBqbUtxRndzQXk=
  # Base64 encoded de exactamente 32 caracteres: "randomcookiesecret32charslong123"
  cookie-secret: cmFuZG9tY29va2llc2VjcmV0MzJjaGFyc2xvbmcxMjM=