apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-config/cluster-issuer.yaml
  - apps/api
  - apps/frontend
  - infrastructure/databases/mongo
  - infrastructure/databases/postgres
  - infrastructure/monitoring
  - infrastructure/auth