---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-secret
  namespace: default
spec:
  encryptedData:
    KEYCLOAK_ADMIN: AgAgv4Vi5tm+jNDky4B0DN/MdK0nL2OwHTERpKz43ZeZTZyJSypa96MvNYCkS0aXZoZZEWjz0Rj+YHkd5KxviqWjMo2vbilPHJBgalxspemkPA+fNHXNwD/lQlwaAIN2dQ6zj35NEM1u5LUbhu4iSp3u1r2ni318J4jD1DwD/WoqQbTY4ziGjFAUUnI3Bw3g86usep/UKxd23Be+hiGgf+Cb0L1N8xPqbqP0bCQmHlLWzBbsNjIPhBQGLfQXsfAwXeltzJQ3qSdQUt5+B2SPggMqmBN6P3a9j0Ssvo7JcBWwTwH/plR9ibo+CakOPzRjMDO0tEIEm0ypJOKhXTQH9t0qBU/LzXzFg2NEIdCZf6iGbPzc/BrQm+yiRzJ4WbOJ1iy9tRmvhEEwQ8XlqAnTIMw3b1UveRjCpScVnqX+C4h9NI6pxlIiT7NBucVTFp2BbFpeCppdS5GRfEWlHGkfRHQbTjcUc4vEW3e2ByPk2VNbZklgLLxecr1JfIzrvyjaSMf2XPQxD/C7xVogJxBEiKsjsb7RE7r5Wf7SMXwbiSQ7xD1bo93ZaTC0ubm7k1T86STFki+6o308S8Kkv+Cj9oOWmjQjdgUNsY2YqzEi8fsko8kVHLkfAHfbwbQS+RasP9hkbxQ6jtOav+ILnnknlJNq8QTxiCZyUmvXJFVWenPyqkh+PZ9mf4v+AsBGIWbBBdzI4lzOiA==
    KEYCLOAK_ADMIN_PASSWORD: AgAY7wLq9GzE6m/L4EhMpsuKkXsCNGrbpX/1qiyVV1NKmf2GzeFRgL3FNmt16fnHFZOEML+iJFrfgAoBFNhhAhHYYonhTqqvWAlsVfB3Pmql8BqlO6++scIfG2U1O0ytiVhTighBB7/fY5Pf8iXM1a/5RC3lxqUqHaXykWJNMdXW1ZvRZod8gfevhaGeztEWWsNO+c8i+zhiI0xEHXuAgzjzyiSG2JKGZDQjKvMTH+skaiRoKrfoUPP6Et2dfo9VMANFBZvj4kzoKkNT/iHFYsje+uQyrxdXDtBh6dWHMuNHZqBtKOalZVTWdCg5qf6s95RQ5SuIFR7TID6KQ6OKb4wcak7N7Utu2KzCQ75UN58ugA5yoRhV34u8uUrW+WJcNTF5X6wh0mg5ea76nMXyTs+S/RLWvQ5PPgwHQ3jP5EZSMlZvGw5bQgi5jHqjbBPCdEzo7Eyf9tEi+wUlg2qlhDxEokzHkJCIPtDXG/j7SXcDJLAlW17yn6JXxddt4akgVqghklWTDzSJQHsrHilAHgjldPizM7KPCcNEE+w1mY3Vi3i1MCGTWM9wvY08I3lvbfVXXFUQbNd2X4l0OVjrAP/ctCupa2afA1UN5hP1ZN5cDcK4WnTI5xvMhI4FHGLWDH5yoBROxpuFM/TBW6oQl6N/n6BB8oxmePacNagsPjgqB0/1M8y20EIPCJixHZsypQcvgdMX1SCbrw==
  template:
    metadata:
      name: keycloak-secret
      namespace: default
    type: Opaque
