---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-secret
  namespace: default
spec:
  encryptedData:
    client-secret: AgBYn5LfNJ26E0q7OZ/FXiLfJ9/YSk83XGYKuWh5dwL+uAFGXKT22j2t1QiOb8NQw8i/d3z5lZ/qWadp2DkBMlu4bbXIhvjBb0lw0sl/cBpseK3xMbkNOiO3yFBd37YEdDA6M/nERzbPvcOlNlE3FX0iJoTN2ciSdYpbDRYgkzH5NflPZn+BeLt7UO5BI4pFd5lAQtEhW/Zp6OGBcS+DJyFUXIjLpu4+yn43w1ezikgCY0Uu0qVXAPJKsoIRQY9e13GRlkuJl6zpYJu2U9qFXRDd/NAroWxwpKwLfaNmD1MK/xxpJW+1BwoaUnyGPeZsAKmGmdWkv5KrQcAVeP0nFkLgaosc1i15fS4No7OptFA5cTSRk3wTvPdVr7cC/KCdy0Ig6n8kQ/UcE8wwT2WzxrnN6abmRxewrYtOMxd3EcizCf+9VhAqI9V3WM7o05urCKqNznaXWSf2Jtv6pe+D8TKgxz1WVHObkpyj80ZSk8M+CHhGHhD1dmQDZhIgDst0S//MU70cxcUD1kdKfOEqzC9TP3VOFcMbhNZhcI+iSEYuSJG99Afr4nZjMQbn9ZIlJZMLeQGMFwcYx/JtA8TKM4gopqyCZYovlTO592Px8w+PGoFVCpRT6sbpqdbSOeda0+FaeMbaCieKoFHPS3pmfX/B1rJ2ADcmBLzJ550DJ74RxM+pLtKWUngQVyV7HDFmMhamKocZshXIvbLO9obpg0Usv1CB5OkELQCmOuHjnORhqw==
    cookie-secret: AgAKkW2YENObbIM+UqswxKJ3SCCCJh5YYCzVXWqHI0IcitqgKomgJrijAFVMSPfGC2sPx9UBcn66RbTGmVV5PtgpPWbrW2AYRTe45vG3n/aECP2aiye0dLMdWwxb1MB3L1tyXgQp2LaQO1PVBcM1OYikhnwZUFMfeAJ3WBbDAz1rUKRUQnX7UlzNsY+z6kvBp7KuxIotlYX8g1ExZzdc1cPbHmQsmN6fTjJPh/uk5nX1UPkzbj1wCDG+vs10JhGh6XWcV5FTxbslY5P64uR/8U4j3/Ywmpy17q+j9VYXtmtTpz5n+xgXBiUNCv822Y/ueAcvHP++jFuB5XZwYm+br5/LEWb6EfxmtWjYLo5CyBnZeScqoKtCm92VFB+zy0zgO9Yx27w1SS8aans9a+0cFbK51eaatrgnbG5GlvgliZCb/V9I2Zy43NUPArnalgY9avgBHAz+VOAeinJRb+uUWEHhQn7lRCK2hjwOVZkGbnwflXBfBckwCuSXLkVnanTfg1SeLf+LZqeNqMYK5ED7DVEYPKKoTbiTibZmTNo/11lb10yOHhdQnYXoXvsCD25VkZy/JuvzzFSQub5nTuAH8JnP3Zakn5llIJ0MXJbCjWv59HAlf1yzquyza8N7a8cUmv52qQcnGpxqynkpf7NmJ+6cFX9erLnP/9JlxTpAIqwdNWGKyj2YJjHgRdT7sejtwIfzzt1ABXCvw538sRK3y6D0FLlS+NGTgRHjHgKypGiCiQ==
  template:
    metadata:
      name: oauth2-proxy-secret
      namespace: default
    type: Opaque
