---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: default
spec:
  encryptedData:
    admin-password: AgBWEJaRmdzAfSSrJf82lvDo1MXb938MsLA/LfCkr3bT73dagQdGY3R4HuOXk+y/99JDYwBoiFy6Jve9hNSAHS4up+03jGu+V6dTCHDrpItTW17nt3sPBvpc9RFxbm3ByLc1oQRWtf+4O/krKcRxN9atRRcBNfcJTra++ZNMKbN8unENVZbGvJCu2JL8cljvGho+LX/RYVqQGMm2M/tsoUc7ZuVgjZMgubidZRFz8bSu09cqUpNz7gbh2XQx3y/XTXH3rEPQli/Npmv/CHeUaaUB3Sj/3Jx03/FbqV+bNWDbu8Zptlq61hBZiVrY9Q0E3sE8zEsiDmK5wQ051OrBMr8H3vqzqmGiVPP23T/oC4oNJ5cvat+eCJFQgipu9XhLMKhVXd7N3Y7MuX8k4/16EIOLevIMmVqlji8zu1f5yg5AdHE2BcyDjXeYtuDKTkLPjGl9Y1RmqBnWW2JkkiKw6NjROpLI+UjRsMNno9C+WAFKVVznOmhssN6rWKBrhTR3o0EqxFU58uVYcPSu8OXwAoQeX8HQq357lawEX84dCDC2k5YSUxOpC6ABF/LzxPnkcLF+gZgTp3d+W3u0xDehq5EYJKR2dGtzr8c1L9poCjswl3oEqsXNSCXo9wHY5ZrSI4wiqts8FPp3bOW7TVDvCcxFPAJ/t3gVxWt2okheQfat8sShQY9Q5uUBq1bD2QIyp0MZoer4rnZ2Nw==
  template:
    metadata:
      name: grafana-secret
      namespace: default
