---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBlqYllG2mTBa+gWiQlUUYzKo/9NKPyqKSR8W/sNFfLUbpfd4OYBBMF9UvFjYWAa0lm32YmdCy8KwoKtSCSNjytAxGwR8S0oCsTIu3tgP67WUDyx9X3/P56eF+alzMci/aZe1sKN9BKghy5iPj0Ir9dqsraqh/kgHgHfn6Gts8T4s2Mb2qaLlngMWcXrofkXD+zkWtZE546OGnZop1GWHpzAxNlPPZ/poi8sKkpir+iAEZxJ1T7/illlcQloLId4hQcc/MrFSFxcCrty5oPsEphPPc6D/lvZ9iSz76BplqBJaWki8jCmPXu8pWc419gLMJpu8xKUeiEumzaBe/ENfufSwyjfLqEpyjGNYj+fao8fxPkIc/aCAA7I6RcCR5tMFqnzDZk781tFckt0maRVGLSCwJLWIQpDVDLeY/dcKHHD0e1ClMoGleeWKfoQIBaB9p53Oj0F7oBTqfaZRk/8roZs5ofqKFx2zmyHVvGLuUObhaadN45lqcWRqUXk11cs/A3Ql8Ek71ruswpXH24gJ36SJdvYiZV9YZzz7kWXZNCwQNZheTH5shJFB8769FdXcXtRcQPElcv/i/K/uLbEq+g5F3dG/OXvJZY5dJ5A5gOSUdHWIUTZJd1G/ZDhMCS8FrawXa6yYxisvIGq9ASXYq/pkNwA6DLbO08B0VihOBhzCW4KZ2WdDpT+XUl70IQnbfcxgpmK0DISnOUVw==
    POSTGRES_USER: AgCIAUgLgo6AX9tCI2HMzMvtxMqQU9JQN3of9GDxDPiasd4ot5TFJLuLTCLFHvq2nlPadFIDIXtrAcTaa3HMqzgQW4Cy1HJTFCm+/K+v8jdgYa587pVNji5rk3H6S5MS0+B8ecRdOdl839qw7CVUWbCpdiEk+flEW86/9PZ3W+nUTtRgkYq+bQditpLNDm7q85ZVG44kD6m98y1Yez32pbI29G9hbLRBcNjuLrzLdXeVJGzcQGfG65lJNc12aN8w1ImC63kk1OY9BtpeE3GV8UkSKRsuombp52RhRA3cVSkAXJeQHnm82L7e5cDhWeBFErDXEpfMtQsribyUJpbWLJXC/t+YEMS4wl84GsUJrts1eaBG/Qa52ezg6Y330RG4DycKQ77Gtwb8f4MiwgMTh9fDQ+P1i/W/hn1PovKM2ljpfBdpxe/CZ24yeEkrtJKVaqKY3EK0+NDdVmARojtsWo6j3nMU1gJlAV1H2Ux/hX519Ng53RaJcQWXzA9DqvgNDkwkCpewTuQ5pssWB81+tJaFrxYyy2DnMm/tg8p/WNukau8vXPGfx3nt/Pmiup/+RUD5oaDVV45uCV3O0gNs6snBv7itB0VQyc7C90A2miM2r3zVtfjCD7pLLHpPBjyYg9JG+eZ1SQXIt9YuMYdf6Bdbl3j/Ebi09ystI2IBRUK69YK5MoogFkaM++BFNXhA3nHY+kGFBzcrcQ==
  template:
    metadata:
      name: postgres-secret
      namespace: default
    type: Opaque
