name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ./Frontend
        push: true
        tags: |
          sincal/task_manager_frontend:${{ github.sha }}
          sincal/task_manager_frontend:latest

    - name: Update Kubernetes Manifest
      run: |
        cd k8s/apps/frontend
        # Update deployment.yaml with new image tag locally for the deployment
        sed -i "s|image: sincal/task_manager_frontend:.*|image: sincal/task_manager_frontend:${{ github.sha }}|" deployment.yaml

    # 1. Instalar doctl (CLI oficial de DigitalOcean)
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    # 2. Obtener credenciales del Cluster
    - name: Save DigitalOcean Kubeconfig
      run: doctl kubernetes cluster kubeconfig save do-nyc1-k8s-1-34-1-do-2-nyc1-1768961352688

    # 3. Aplicar los cambios al Cluster REAL
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -k k8s/apps/frontend
        kubectl rollout status deployment/frontend-deployment -n default

    # 4. (Opcional) Guardar el cambio de versi√≥n en el repositorio git
    - name: Commit and Push version update
      if: success()
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add k8s/apps/frontend/deployment.yaml
        git commit -m "Deploy: Update frontend image to ${{ github.sha }}"
        git push
