---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secret
  namespace: default
spec:
  encryptedData:
    MONGO_URL: AgBtPhxRIFgms/e++M3XkbIeN8r80/UX7WNhOajOmfPy9n4yYEZk805/sZu8ubN+pid0Z8kgOJr7L/WqG+rISE7B9HWHM7F+tMC6nrOsS0Fl1Hzrkxl+Ku4kraZGXfOrZZ1mBv3r8PL2b/UEXOfuiFgQbIwygkscXcsxteF2Ap8bonaoewArR1uEBfSfKYnfaKngtQOYo1SR0Fft8wvCmDC77hPXN7lyiiMmIm3Ui9PH4gNE2ZbYLrKW+vtO11wsDGTmMrUZAmIIbc5gmRPH51Z5OGeagiqpsdQ3s2ueK7QInn0gQyg7GC5+9LhgZwFWKybvdqRmzL9BAw1M2MxyQRi1n5FIEhMit+w1vmQO5CGV2F1ZabCeVDh/VJzGKcXDwCnBhIwXFPJEbptIzL7ih82un5tjWZy6isodx500pIFG8PlsRWtVYb/dutlzIpSEG7mTXG+Tm98VZ1FsD0nT7nyDjPJoc/h0xa05A4rw7lN4Pz0w+sKxQKSnw1BA1K2QzfH2ULWNEFpISluB615d/KOPCWnC6G4DH+bdmoAlEMemZyUqAL4dqWLsAKxxAfFRMLZKP4cmW5QvxojIB41l1xnQEuD9FCg6SVokGxuo6ExBCPGYq3Nepkn8lkFdegnQb88B/6BBF1e63y4GqCwYSEgdWlXUlsQaici3f1Muicf+J+qO7L+c9qAzDOViEyEaXlxcrLqACtIN0OADi9YAeQT5TykLd5/hMbDY8fyraVYTb1MfjR79iTFIjCXj5osHThDA7wD9oddf6fbDGZkxr2gnZ6OBjmRcrZW/RjGh
  template:
    metadata:
      name: api-secret
      namespace: default
    type: Opaque
